spring.profiles.active: default

server:
  port: 8080

spring:
  datasource.url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
